### ISSUE TITLE
Algorithm builder

### ISSUE THREAD

**Issue by Oldsirhippy** [justpliz/DHT11-Display#1]
Where did you get algorithm builder? 
All sites tried have so far failed...

**Comment by justpliz** [comment]
> Where did you get algorithm builder? All sites tried have so far failed...

Sorry, I just saw your question. I don't know if it's relevant, but I wrote this for my bachelor's thesis.
https://cxem.net/software/algorithm_builder.php

**Comment by Oldsirhippy** [comment]
Hi Abay,

Thanks for your message.
Unfortunately Google said it could not translate the link you sent, so I
couldn't read it.

Gennady Gromov who wrote the algorithm builder is no longer contactable, I
have tried various ways to get in touch with him but have had no success.

The software can be downloaded from some Russian sites but not on the
algrom.net site as it is defunct for that purpose.

From a glance at what you wrote - have you used Algorithm builder?

Kind regards

Phil.

Phil Sydor
email: ***@***.***

Always remember that you are absolutely unique. Just like everyone else.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_5344024932037874941_m_-7893993490225350172_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
